### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [ricardbejarano/cloud-torrent#1]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by ricardbejarano** [comment]
Yes, but the upstream repository it builds a Docker image for ([jpillora/cloud-torrent](https://github.com/jpillora/cloud-torrent)) doesn't seem to be.

Feel free to submit any improvements you may find useful.

**Comment by ghost** [comment]
Hi ricardbejarano.

> Yes, but the upstream repository it builds a Docker image for ([jpillora/cloud-torrent](https://github.com/jpillora/cloud-torrent)) doesn't seem to be.
> Feel free to submit any improvements you may find useful.

thank you for feedback.
